version: '3.8'

networks:
  canchu-network:
    driver: bridge

services:
  canchu:
    image: canchu
    environment:
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql-container
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=22Pilots71416!
      - MYSQL_DATABASE=user
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql
    networks:
      - canchu-network

  redis:
    image: redis:6.0-alpine
    command: redis-server --requirepass ''    
    ports:
      - "6380:6379"
    networks:
      - canchu-network

  mysql:
    image: mysql:5.7.42
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=22Pilots71416!
      - MYSQL_DATABASE=user
    ports:
      - "3306:3306"
    networks:
      - canchu-network
