version: '3.8'

networks:
  canchu-network:
    driver: bridge

services:
  canchu:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - redis
      - mysql
    networks:
      - canchu-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - canchu-network

  redis:
    image: redis:6.0-alpine
    command: redis-server --requirepass ''    
    environment:
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      DATABASE_HOST: ${DB_HOST}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: user 
    ports:
      - "6380:6379"
    networks:
      - canchu-network

  mysql:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    networks:
      - canchu-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: user
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: bind
        source: ./mysql-init-scripts/init_test.sql
        target: /docker-entrypoint-initdb.d/init_test.sql
      - type: bind
        source: ./mysql-init-scripts/init_user.sql
        target: /docker-entrypoint-initdb.d/init_user.sql
      - type: bind
        source: ./mysql-init-scripts/permission.sql
        target: /docker-entrypoint-initdb.d/permission.sql
      - mysql:/var/lib/mysql

volumes:
  mysql:
