version: '3.8'

networks:
  canchu-network:
    driver: bridge

services:
  canchu:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql
    networks:
      - canchu-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - canchu-network

  redis:
    image: redis:6.0-alpine
    command: redis-server --requirepass ''    
    environment:
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      DATABASE_HOST: ${{ secrets.CANCHU_SECRET }}
      DATABASE_USER: ${{ secrets.CANCHU_SECRET }}
      DATABASE_PASSWORD: ${{ secrets.CANCHU_SECRET }}
      DATABASE_NAME: user 
    ports:
      - "6380:6379"
    networks:
      - canchu-network

  mysql:
    image: mysql:8.0.34
    env_file:
      - ./mysql-init-scripts/.env
    ports:
      - "3306:3306"
    networks:
      - canchu-network
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.CANCHU_SECRET }}
      MYSQL_DATABASE: user
      MYSQL_USER: ${{ secrets.CANCHU_SECRET }}
      MYSQL_PASSWORD: ${{ secrets.CANCHU_SECRET }}
    volumes:
      - type: bind
        source: ./mysql-init-scripts/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
      - type: bind
        source: ./mysql-init-scripts/privileges.sql
        target: /docker-entrypoint-initdb.d/privileges.sql
      - mysql:/var/lib/mysql

volumes:
  mysql:
