version: '3.8'

networks:
  canchu-network:
    driver: bridge

services:
  canchu:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql
    environment:
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: canchu_mysql_1
    networks:
      - canchu-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_docker/certificate.crt:/etc/ssl/certificate.crt
      - ./nginx_docker/private.key:/etc/ssl/private.key
    networks:
      - canchu-network

  redis:
    image: redis:6.0-alpine
    command: redis-server --requirepass ''    
    environment:
      REDIS_HOST: canchu_redis_1
      REDIS_PORT: 6379
      DATABASE_HOST: canchu_mysql_1
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: user 
    ports:
      - "6380:6379"
    networks:
      - canchu-network

  mysql:
    image: mysql:8.0.34
    container_name: canchu_mysql_1
    env_file: .env
    ports:
      - "3307:3306"
    networks:
      - canchu-network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=user
    volumes:
      - type: bind
        source: ./mysql-init-scripts/init_test.sql
        target: /docker-entrypoint-initdb.d/init_test.sql
      - type: bind
        source: ./mysql-init-scripts/init_user.sql
        target: /docker-entrypoint-initdb.d/init_user.sql
      - type: bind
        source: ./mysql-init-scripts/permission.sql
        target: /docker-entrypoint-initdb.d/permission.sql
      - mysql:/var/lib/mysql

volumes:
  mysql:
