name: dispatch receiver

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      if: github.event.pull_request.number == github.event.client_payload.pull_request_number
      run: |
        echo "repository_dispatch triggered"