name: Canchu

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write
  
jobs:
  canchu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup sql .env variables
        run: |
          ls
          cd ./students/steven/Canchu
          echo "${{ secrets.CANCHU_SECRET }}" > .env
          cd mysql-init-scripts
          echo "${{ secrets.CANCHU_SECRET }}" > .env

      - name: Setup nginx .env variables
        run: |
          ls
          cd ./students/steven/Canchu
          mkdir nginx_docker
          echo "${{ secrets.CANCHU_NGINX_CERTIFICATE }}" > nginx_docker/certificate.crt
          echo "${{ secrets.CANCHU_NGINX_KEY }}" > nginx_docker/private.key

      - name: Docker Compose Up
        run: |
          ls
          cd ./students/steven/Canchu
          docker-compose up --build -d

      - name: Wait for setup
        run: sleep 15

      - name: Run test
        run: |
          ls
          cd ./students/steven/Canchu
          docker ps -a
          docker exec canchu_canchu_1 npm test
          docker-compose down
          docker volume prune
          docker system prune -a
          
  canchu_deploy:
    needs: canchu
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: "${{ secrets.EC2_HOST }}"
        username: "${{ secrets.EC2_USERNAME }}"
        key: "${{ secrets.EC2_KEY }}"
        script: |
          cd assignment0706/Campus-Summer-Back-End/students/steven/Canchu
          git pull
          ls
          echo "${{ secrets.CANCHU_SECRET }}" > .env
          cd mysql-init-scripts
          echo "${{ secrets.CANCHU_SECRET }}" > .env
          cd ..
          if [ ! -d "nginx_docker" ]; then
            mkdir nginx_docker
          fi
          echo "${{ secrets.CANCHU_NGINX_CERTIFICATE }}" > nginx_docker/certificate.crt
          echo "${{ secrets.CANCHU_NGINX_KEY }}" > nginx_docker/private.key
          docker-compose up --build -d

      
