name: Canchu

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Put into secrets
        run: |
          ls
          cd ./students/steven/Canchu
          echo "${{ secrets.CANCHU_SECRET }}" > .env

      - name: Docker Compose Up
        run: |
          ls
          cd ./students/steven/Canchu/mysql-init-scripts
          echo "${{ secrets.CANCHU_SECRET }}" > .env
          cd ..
          ls
          docker-compose up --build
